### ISSUE TITLE
Why is the `n` of `hoist` not a monad?

### ISSUE THREAD

**Issue by nikita-volkov** [Gabriella439/Haskell-MMorph-Library#11]
I mean, why

``` haskell
hoist :: Monad m => (forall a. m a -> n a) -> t m b -> t n b
```

instead of

``` haskell
hoist :: (Monad m, Monad n) => (forall a. m a -> n a) -> t m b -> t n b
```

?

I've stumbled upon that trying to implement `MMonad` in terms of [this function](https://github.com/nikita-volkov/cereal-plus/blob/f1bb9578f253b9d4f50c1edf76323a998941a1ca/src/CerealPlus/Deserialize.hs#L56-L63).

**Comment by treeowl** [comment]
Here's another one: the `free` package defines

```haskell
hoistFT :: (Monad m, Monad n) => (forall a. m a -> n a) -> FT f m b -> FT f n b
hoistFT phi (FT m) = FT (\kp kf -> join . phi $ m (return . kp) (\xg -> return . kf (join . phi . xg)))
```

If there's a way to weaken that to `Monad m`, I haven't been able to find it. I suspect the "work from the inside out" approach may be defeated by this Yoneda-style type.

**Comment by Gabriel439** [comment]
@treeowl: Yeah, for the efficient implementation you require the `Monad n` constraint.  In theory you can still do it inefficiently by converting to `Control.Monad.Trans.Free.FreeT` and then converting back

The problem is that adding the `Monad n` constraint breaks the `Control.Monad.Trans.Compose` module

**Comment by treeowl** [comment]
I don't think you can convert back.

**Comment by Gabriel439** [comment]
You can, using `Control.Monad.Trans.Free.Church.{toFT,fromT}`, but I just realized it still doesn't work anyway because you still need the `Monad n` constraint for `toFT`

**Comment by treeowl** [comment]
> The problem is that adding the Monad n constraint breaks the Control.Monad.Trans.Compose module

While this isn't quite complete, one option is to use `constraints`:

```haskell
instance (MFunctor f, MonadTrans f, Lifting Monad g, MonadTrans g) => MonadTrans (ComposeT f g)
  where
    lift :: forall m a. Monad m => m a -> ComposeT f g m a
    lift = ComposeT . hoist lift . lift   \\ (lifting :: Monad m :- Monad (g m))
```

This requires a `Lifting` instance for each inner transformer. While that's unfortunate, I'm not convinced that it's more unfortunate than failing to support `FT` from `free`. There is even some cause to hope that GHC may eventually be able to provide built-in support for `Lifting` thanks to recent research on implication constraints.

**Comment by Gabriel439** [comment]
@treeowl: There's yet another issue, which is that adding a `Monad n` constraint will break the use case that fixing #29 was designed to solve (i.e. the case where `n` has kind `k -> *`).  Adding the `Monad n` constraint would force `k` to be `*`, defeating the purpose of making the class poly-kinded

**Comment by treeowl** [comment]
I don't understand what this polykinded thing has to do with monad
morphisms. The `rmap` example seems a bit silly, since `hoist` is already
too restrictive to do everything `rmap` can.

On Thu, Aug 24, 2017 at 10:34 PM, Gabriel Gonzalez <notifications@github.com

**Comment by Gabriel439** [comment]
Either way, adding the `Monad n` constraint would be yet another a breaking change due to previously enabling `PolyKinds`

I also would still like to keep the constraints on the use of `hoist` as small as possible

**Comment by Gabriel439** [comment]
Actually, even without considering `PolyKinds` adding the `Monad n` constraint is still a breaking change to the API (since there may be some call sites in the wild where `n` is not a `Monad`)

**Comment by turion** [comment]
I just stumbled over the `mmorph` example. Even if you implement, as suggested this function:

```haskell
unviewT :: Monad n => ProgramViewT instr n a -> ProgramT instr n a
unviewT (Return a) = return a
unviewT (instruction :>>= continuation) = singleton instruction >>= continuation
```

...you still need the `Monad n` constraint on the target monad. I'd like to use `mmorph` and add an `MFunctor` instance, but unfortunately like this it won't work. Can we reopen and reconsider?

**Comment by Gabriel439** [comment]
@turion: I believe you can implement `MFunctor` for `ProgramT`, like this:

```haskell
instance MFunctor (ProgramT instr m) where
    hoist nat (Lift   m) = Lift (nat m)
    hoist nat (Bind m f) = Bind (hoist nat m) (\x -> hoist nat (f x))
    hoist _   (Instr  i) = Instr i
```

I have not type-checked that, though

**Comment by turion** [comment]
You are right indeed! Thank you very much.

**Comment by Gabriel439** [comment]
You're welcome! 🙂
