### ISSUE TITLE
Possibly add `ComposeT`

### ISSUE THREAD

**Issue by Gabriella439** [Gabriella439/Haskell-MMorph-Library#4]
John Wiegley suggested a higher-order version of `Data.Functor.Compose` for `mmorph`.  I'm pasting the code that he e-mailed me here so other people can comment on it:

``` haskell
   newtype ComposeT (f :: (* -> *) -> * -> *) (g :: (* -> *) -> * -> *) m a
        = ComposeT { getComposeT :: f (g m) a }
        deriving (Functor, Applicative, Monad, MonadIO)

    instance (MFunctor f, MonadTrans f, MonadTrans g)
             => MonadTrans (ComposeT f g) where
        lift = ComposeT . hoist lift . lift

    instance (MonadIO (f (g m)), Applicative (f (g m)))
             => MonadBase IO (ComposeT f g m) where
        liftBase = liftIO

    instance (Applicative (f (g m)), MonadBaseControl IO (f (g m)),
              MonadIO (f (g m)))
             => MonadBaseControl IO (ComposeT f g m) where
        newtype StM (ComposeT f g m) a = StMComposeT (StM (f (g m)) a)
        liftBaseWith f =
            ComposeT $ liftBaseWith $ \runInBase -> f $ \k ->
                liftM StMComposeT $ runInBase $ getComposeT k
        restoreM (StMComposeT m) = ComposeT . restoreM $ m
```

I probably wouldn't do `MonadBaseControl` or `MonadBase` instances, but the other instances seem really useful.  I also wonder if `ComposeT` can be made an instance of `MMonad`.

**Comment by RyanGlScott** [comment]
Apologies for reviving an ancient issue, but I took notice of your comment:

> It is kind of lame that there is no easy way to indicate a constraint like `forall m . (Monad m) => Monad (g m)`.

This is actually possible using the upcoming [`QuantifiedContexts`](https://github.com/ghc-proposals/ghc-proposals/pull/109) GHC extension! This typechecks using [this GHC branch](http://git.haskell.org/ghc.git/shortlog/refs/heads/wip/T2893):

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE QuantifiedConstraints #-}
{-# LANGUAGE RankNTypes #-}
module Foo where

import Control.Monad.Trans.Class

newtype ComposeT (f :: (* -> *) -> * -> *) (g :: (* -> *) -> * -> *) m a
  = ComposeT { getComposeT :: f (g m) a }
  deriving (Functor, Applicative, Monad)

class MFunctor t where
    hoist :: (Monad m) => (forall a . m a -> n a) -> t m b -> t n b

instance (MFunctor f, MFunctor g, forall m. Monad m => Monad (g m))
    => MFunctor (ComposeT f g) where
  hoist f (ComposeT m) = ComposeT (hoist (hoist f) m)
```

Moreover, you can use `QuantifiedConstraints` to write a much cleaner `MonadTrans` instance for `ComposeT`:

```haskell
instance (MonadTrans f, MonadTrans g, forall m. Monad m => Monad (g m))
    => MonadTrans (ComposeT f g) where
  lift = ComposeT . lift . lift
```

Something to look forward to. (In GHC 8.6?)

**Comment by baskaransri** [comment]
GHC 8.6 is here, along with Quantified Constraints. I'd be interested in the automatic instances and can do any grunt work needed.

**Comment by Gabriel439** [comment]
@baskaransri: Yeah, go for it! 🙂

**Comment by baskaransri** [comment]
Questions:
1) Would you want the cleaner MonadTrans instance as well as the MFunctor instance?
(the cleaner MonadTrans instance above replaces the MFunctor constraint on f with the forall constraint)
2) Would this require a major version bump or a minor version bump?

**Comment by Gabriel439** [comment]
@baskaransri: Yes, I would prefer the cleaner `MonadTrans` instance, and that would require a major version bump but I would be okay with that.

**Comment by RyanGlScott** [comment]
I'm jumping into this discussion somewhat late, but what is the backwards compatibility story here? #39, as it currently stands, won't work on any version of GHC but 8.6 or later, which seems unfortunate. I can see two ways around this:

1. Use CPP such that the `QuantifiedConstraints` type signature is used on GHC 8.6 or later, but fall back on the original `MFunctor` type signature on older GHCs. This does have the disadvantage that API would be completely different depending on which version of GHC you're using.
2. Provide a copy of `Control.Monad.Trans.Compose` (with a slightly different name) that uses `QuantifiedConstraints` in its `MonadTrans`/`MFunctor` instances, and only export that module on GHC 8.6 or later.

I'd personally lean towards option 2, although I'm not a maintainer of this package—I'm just some schmuck on the Internet :)

**Comment by Gabriel439** [comment]
Alternatively, we could stick with the older `Compose` instance and move the newer instance to a separate package that is more appropriate.  If I remember correctly, the main reason that `ComposeT` was in this package was because it relied on the `MFunctor` constraint to work, but if it doesn't use `MFunctor` then maybe the new version using quantified constraints should reside in a different package
